language: c
os:
  - osx

# XXX Doesn't work on OS X VM's currently (Nov 2015).
cache:
  directories:
  - $HOME/.stack

env:
  - PATH=$HOME/.local/bin:$PATH

before_install:
  - mkdir -p ~/.local/bin
  # Passing -k to work around https://github.com/travis-ci/travis-ci/issues/4709.
  - travis_retry curl -Lk https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin

install:
  - brew update
    # ignore bad exit status.
  - brew install gcc --force || return 0
  - brew link --overwrite gcc
  - brew install --force r zeromq
  - pip install ipython==5.5.0
  - stack setup
  - stack --no-terminal -j2 build --only-snapshot --prefetch --test --bench

script:
  # XXX no tests for now since it times out.
  - stack --no-terminal -j2 build --pedantic
